verify_x_post:
  description: >
    Verifique se o post X fornecido atende aos seguintes critérios:
    - Deve ter entre 200 e 280 caracteres, inclusive.
    - Não deve conter emojis.
    - Deve conter apenas o post em si, sem comentários adicionais.

    O post deve seguir a regra 1-3-1:
    - 1 declaração ousada para atrair o leitor
    - 3 linhas de informações de apoio
    - 1 frase para resumir o post

    Além disso, se você acredita que há problemas com o post
    ou maneiras de melhorá-lo, como a estrutura do post,
    ritmo, escolha de palavras, por favor, forneça feedback.

    Se algum dos critérios não for atendido, o post é considerado inválido.
    Forneça mudanças acionáveis sobre o que está errado e quais ações
    precisam ser tomadas para corrigir o post.

    Sua resposta final deve incluir:
    - Válido: Verdadeiro/Falso
    - Feedback: Forneça comentários se o post falhar em algum dos critérios.

    Post X para Verificar:
    {x_post}
  expected_output: >
    Pass: True/False
    Feedback: Comentários aqui se falhar.
  agent: x_post_verifier